functionSecretConfig:
  debugToken: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcHBpZCI6InJqYjAwbCIsInR5cGUiOiJkZXZlbG9wIiwiZXhwIjoxNjgxNDE2MjE3LCJpYXQiOjE2ODA4MTE0MTd9.s_K2Jbt7UOd2Meat5h-2oyZ8sTABDuws2gbG6Eg9msY
  debugTokenExpire: 1681416216
storageSecretConfig:
  endpoint: https://oss.laf.run
  accessKeyId: U49EQBYI1JADVT9GRX21
  accessKeySecret: HVuHI7l5bxMA0IV9+AIKw2Kaw174Q47dJFzW7iI0
  sessionToken: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NLZXkiOiJVNDlFUUJZSTFKQURWVDlHUlgyMSIsImV4cCI6MTY4MTQxNjIxNiwicGFyZW50IjoicmpiMDBsIiwic2Vzc2lvblBvbGljeSI6ImV5SldaWEp6YVc5dUlqb2lNakF4TWkweE1DMHhOeUlzSWxOMFlYUmxiV1Z1ZENJNlczc2lVMmxrSWpvaVlYQndMWE4wY3kxbWRXeHNMV2R5WVc1MElpd2lSV1ptWldOMElqb2lRV3hzYjNjaUxDSkJZM1JwYjI0aU9pSnpNem9xSWl3aVVtVnpiM1Z5WTJVaU9pSmhjbTQ2WVhkek9uTXpPam82S2lKOVhYMD0ifQ.TR0UEN6KHiICe3CSjtPGjSvBDcbprmefxBSpgaChcdEsLDgCKgrQ9ZO3Uax7c57rRloxZdEtl-_5FkOaftCuww
  expire: 1681416216
